[package]
name = "xactserver"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
bytes = { version = "1.0.1", features = ['serde'] }
clap = "2.33.0"
env_logger = "0.9.0"
futures = "0.3.17"
log = "0.4.14"
prost = "0.9"
tonic = "0.6"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync"] }
tokio-stream = "0.1"
zenith_utils = { git = "https://github.com/zenithdb/zenith.git", package = "zenith_utils" }

[build-dependencies]
tonic-build = "0.6"